import { Athlete } from "@/types";
import { NextRequest, NextResponse } from "next/server";

const athlets: Athlete[] = [
    {id: "ola-nor-123", gender: "Hankjønn", sport: "Sykling", maxHeartRate: 44, thresholdWattage: 44, thresholdSpeed: 44, competitions: [{id: "wasd", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], goals: [{id: "dsaw", title: "Ny maks fart", date: new Date("2023-12-05"), goal: 23, comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], sessions: [{id: "plple", date: new Date("2024-05-23"), title: "Legs", type: "Running", tags: ["Uphill", "Terrain"], report: {id: "njan-tras-5321", status: "low"}}, {id: "plple2", date: new Date("2024-05-24"), title: "Legs", type: "Sykling", tags: ["Uphill", "Rough"], report: {id: "njan-tras-5321", status: "low"}}]},
    {id: "ale-bar-432", gender: "Hankjønn", sport: "Sykling", maxHeartRate: 44, thresholdWattage: 44, thresholdSpeed: 44, competitions: [{id: "wasd", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}, {id: "dsaw", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}, {id: "plple", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], goals: [{id: "plple", title: "Ny maks fart", date: new Date("2023-12-05"), goal: 23, comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], sessions: [{id: "plple",date: new Date("2024-05-23"), title: "Legs", type: "Sykling", tags: ["Uphill", "Rough"]}]},
    {id: "nor-hem-465", gender: "Hankjønn", sport: "Sykling", maxHeartRate: 44, thresholdWattage: 44, thresholdSpeed: 44, competitions: [{id: "wasd", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}, {id: "dsaw", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], goals: [{id: "plple", title: "Ny maks fart", date: new Date("2023-12-05"), goal: 23, comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}, {id: "plple", title: "Ny maks fart", date: new Date("2023-12-05"), goal: 23, comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], sessions: [{id: "plple", date: new Date("2024-05-23"), title: "Legs", type: "Sykling", tags: ["Uphill", "Rough"], report: {id: "njan-tras-5321", status: "no"}}]},
    {id: "noa-ble-783", gender: "Hankjønn", sport: "Sykling", maxHeartRate: 44, thresholdWattage: 44, thresholdSpeed: 44, sessions: [{id: "plple", date: new Date("2024-05-23"), title: "Legs", type: "Sykling", tags: ["Uphill", "Rough"], report: {id: "njan-tras-5321", status: "no"}}, {id: "plple", date: new Date("2024-05-23"), title: "Legs", type: "Sykling", tags: ["Uphill", "Rough"], report: {id: "njan-tras-5321", status: "no"}}]},
    {id: "tur-kle-546", gender: "Hankjønn", sport: "Sykling", maxHeartRate: 44, thresholdWattage: 44, 
    thresholdSpeed: 44, competitions: [
        {id: "wasd", title: "Tour de france", date: new Date("2023-12-05"), location: "Halden", 
        goal: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna. Quisque fermentum turpis quis massa convallis, vel consectetur odio tincidunt.", 
        type: "Sykkling", priority: "A", comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], 
        goals: [{id: "dsaw", title: "Ny maks fart", date: new Date("2023-12-05"), goal: 23, 
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit tristique tortor, vel hendrerit urna."}], 
        sessions: [{id: "plple", date: new Date("2024-05-23"), title: "Legs", type: "Sykling", tags: ["Uphill", "Rough"], "questions": [
            {"text": "What is the capital of France?", type: "radio"},
            {"text": "Who is the author of \"To Kill a Mockingbird\"?", type: "emoji"},
            {"text": "What is the main component of Earth's atmosphere?", type: "text"},
            {"text": "When did the first human land on the moon?", type: "emoji"},
            {"text": "What is the powerhouse of the cell?", type: "text"}
          ], intervals: [{duration: 4, intensityZone: 3}, {duration: 14, intensityZone: 2}, {duration: 8, intensityZone: 1}, {duration: 4, intensityZone: 2}, {duration: 10, intensityZone: 5}], parameters: ["intensity", "speed", "wattage"]}]}

]

export function GET(requet: NextRequest, context: any) {
    const { athleteId } = context.params;
    const athlet = athlets.find(({ id }) => id === athleteId);

    return NextResponse.json(
        {data: athlet},
        {status: 200});
}